### ISSUE TITLE
Not including some stdcells in genus node?

### ISSUE THREAD

**Issue by ctorng** [mflowgen/mflowgen#102]
Why doesn't the worst case look for LVTs/ULVTs/PM stdcells when the other cases do?

- https://github.com/mflowgen/mflowgen/blob/27c082866a82b36a74eec5e241736ce4a4cea632/steps/cadence-genus-genlib/scripts/set_libs.tcl#L65-L70

**Comment by jjthomas** [comment]
@steveri Any idea about this one?

**Comment by steveri** [comment]
> @steveri Any idea about this one?

Oops, sorry, didn't see your message until just now.
No idea, off the top of my head.
I don't think this was my doing, but I'll look at it more closely later, to make sure...

**Comment by steveri** [comment]
Short story: I still don't know why it's there, but I know where it came from. I originally copied this code from `cadence-innovus-flowsetup/setup.tcl`, where it still exists today:
https://github.com/mflowgen/mflowgen/blob/master/steps/cadence-innovus-flowsetup/setup.tcl
```
% less steps/cadence-innovus-flowsetup/setup.tcl
...
if {[file exists $vars(adk_dir)/stdcells-wc.lib]} {
  set vars(libs_wc,timing)    [join "
                                $vars(adk_dir)/stdcells-wc.lib
                                [glob -nocomplain $vars(adk_dir)/iocells-wc.lib]
                                [glob -nocomplain inputs/*ss*.lib]
                                [glob -nocomplain inputs/*SS*.lib]
                              "]
  lappend vars(library_sets)  "libs_wc"
}
...
```

Long story:

Before it was `set_libs.tcl`, it was `designer-interface.tcl`
```
commit a98db997f7b393ffe42949adcc7d2ae621081e56
Author: steveri <steveri@steveri.com>
Date:   Thu Dec 24 06:42:08 2020 -0800

copy from steps/cadence-genus-synthesis/scripts/designer-interface.tcl
copy to steps/cadence-genus-genlib/scripts/set_libs.tcl
```

...and before it was `designer-interface.tcl`, it was `main.tcl`
```
commit 108f2c032e1ffce28f5003003897a5aeb1c3ff64
Author: Alex Carsello <alex.carsello@gmail.com>
Date:   Mon Sep 28 12:21:11 2020 -0700

copy from steps/cadence-genus-synthesis/scripts/main.tcl
copy to steps/cadence-genus-synthesis/scripts/designer-interface.tcl
```

Somewhere along the line, these useful comments got deleted by some idiot (yes, it was me). Lesson learned: don't delete useful comments!!
```
commit a98db997f7b393ffe42949adcc7d2ae621081e56
Author: steveri <steveri@steveri.com>
Date:   Thu Dec 24 06:42:08 2020 -0800

copy from steps/cadence-genus-synthesis/scripts/designer-interface.tcl
copy to steps/cadence-genus-genlib/scripts/set_libs.tcl

-# Steveri update Aug 2020: fixed library load ordering.
-# For consistency, using code similar to what I found in
-# existing step 'cadence-innovus-flowsetup/setup.tcl'

commit c6c6780a77cac51a198cb49aca6fb28cbb95ac90
Author: steveri <steveri@steveri.com>
Date:   Mon Aug 31 08:54:19 2020 -0700

-# FIXME This could maybe could/should be wrapped up as a separate common
-# script somewhere? For use by both genus and flowsetup etc?
-# Better: Could be an executable bash script in e.g. "adks/bin"...?
```

**Comment by ctorng** [comment]
Ouch... can we add wc to both places?

**Comment by steveri** [comment]
> Ouch... can we add wc to both places?

I'm not really the one to ask, since I don't really understand standard cells and corners so well...so far I've just been copying and pasting what others have done...but I assume maybe it's just a matter of changing
```
            $vars(adk_dir)/stdcells-wc.lib
```
to
```
            $vars(adk_dir)/stdcells-wc.lib
            [lsort [glob -nocomplain $vars(adk_dir)/stdcells-lvt-wc.lib]]
            [lsort [glob -nocomplain $vars(adk_dir)/stdcells-ulvt-wc.lib]]
            [lsort [glob -nocomplain $vars(adk_dir)/stdcells-pm-wc.lib]]
```
plus maybe verifying that those newly-identified libraries `stdcells-{lvt,ulvt,pm}-wc.lib` do actually exist?

If the knowledgeable person were to say "Yes, that's exactly what you do," I can certainly do it...

**Comment by ctorng** [comment]
That is exactly what you do. =)

And it won't make a difference to our flow which is not using wc right now.

**Comment by steveri** [comment]
> That is exactly what you do. =)
> 
> And it won't make a difference to our flow which is not using wc right now.

Thanks Chris! Everyone please see proposed fix here: git pull https://github.com/mflowgen/mflowgen/pull/103

**Comment by steveri** [comment]
Fixed, see https://github.com/mflowgen/mflowgen/pull/103
Should we close this issue?
