### ISSUE TITLE
LVS fails silently.

### ISSUE THREAD

**Issue by steveri** [mflowgen/mflowgen#106]
Problem: LVS fails silently.

Mflowgen `LVS` step exits with zero (good) status regardless of whether LVS passed or failed. To see if LVS passed, you have to do something like
```
  % grep INCORRECT lvs.report && exit 13 || exit 0
```
This problem could be solved fairly easily by adding a postcondition error like
```
  assert 'INCORRECT' not in File('lvs.report')
```
*except that* in pipelines (like ours) that use hierarchical builds, the failure does not get flagged. Example:
* build does a step "make tile_array"
* "make tile_array" builds a subgraph including "make Tile_PE"
* "make Tile_PE" runs an LVS step as part of its build; the LVS step fails
* because it happened in a subgraph, and a valid (albeit incorrect) gds output file was produced for Tile_PE, the make continues happily on.

My current solution/hack: after running "make tile" I do something like
```
    for f in `find . -name lvs.report` do
       grep INCORRECT lvs.report && exit 13 || exit 0
    done
```
My better idea: subgraph errors should bubble up to the top graph (maybe this needs to be a separate issue).

Other ideas?

**Comment by ctorng** [comment]
That's a good point. You're right, we currently just mark LVS complete if the report is generated, but it seems to make more sense to mark it "not done" if it is incorrect.

I think it is a great idea to add an assertion to the node, at the very least.

On the other hand, the DRC node probably shouldn't have any assertion (manual fixing is common). So just adding an assertion to LVS sounds great.

**Comment by steveri** [comment]
Manual fixing is not a problem, even if you have the assertion. The assertion just flags the error, you can still choose to ignore it and move forward. 

As an action item, I will add an assertion to the LVS node and (for now at least) I will leave the DRC node alone.

Just to be clear: is a failed assertion enough to mark a node as 'not done'?

**Comment by ctorng** [comment]
Yep, failed postcondition means the node is NOT done.

**Comment by steveri** [comment]
Filed a git pull to address this issue (finally), see https://github.com/mflowgen/mflowgen/pull/107
