### ISSUE TITLE
integrate skywater-130nm-adk

### ISSUE THREAD

**Issue by proppy** [mflowgen/mflowgen#126]
It would be nice to integrate @priyanka-raina https://code.stanford.edu/ee272/skywater-130nm-adk w/ this repo and add a new flow generation script to `designs/GcdUnit`.

Do you think this should be best done with?
- a submodule
- a sibling repo in the @mflowgen org
- a git subtree maintained directerly in the mflowgen repo

**Comment by ctorng** [comment]
Cleaning up this issue, since we did this a while back in #127 and in https://github.com/mflowgen/skywater-130nm . Thanks!
