### ISSUE TITLE
synopsys-dc-synthesis test-12 failed

### ISSUE THREAD

**Issue by hanm2019** [mflowgen/mflowgen#138]
the `make synopsys-dc-synthesis` report the test12 is failed. 

the clock_gating.rpt as follow:
```
                             Clock Gating Summary
          ------------------------------------------------------------
          |    Number of Clock gating elements    |       17         |
          |                                       |                  |
          |    Number of Gated registers          |   262 (23.31%)   |
          |                                       |                  |
          |    Number of Ungated registers        |   862 (76.69%)   |
          |                                       |                  |
          |    Total number of registers          |     1124         |
          ------------------------------------------------------------
```
I read the `mflowgen-check-postconditions.py` file and `assertion_helpers.py` file. It seem the the test12 expect the clock gated registers is more than 50%.  Could you please provide me with more information on this threshold setting?

**Comment by alexcarsello** [comment]
In this case, the threshold setting is somewhat arbitrary. It is just meant to inform you if DC wasn't able to infer clock gates for a lot of registers in your design, which could indicate a problem with your input rtl. You're free to ignore this check by running `make -t <# of synth step>` to mark it as built and continuing on with your flow. You could also make your own DC synthesis node to remove the check entirely.
