### ISSUE TITLE
make cadence-innovus-debug-calibre have a error,but I've already set the environment variables "CALIBRE_HOME"  why?

### ISSUE THREAD

**Issue by sujf** [mflowgen/mflowgen#153]
(venv) [sujf@ic build]$ make cadence-innovus-debug-calibre
mkdir -p 25-cadence-innovus-debug-calibre/outputs && set -o pipefail && /home/sujf/Documents/digital/mflowgen-master/mflowgen/scripts/mflowgen-letters -c -t cadence-innovus-debug-calibre && chmod +x .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-run && cp -f .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-run 25-cadence-innovus-debug-calibre && if [[ -e .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-debug ]]; then chmod +x .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-debug && cp -f .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-debug 25-cadence-innovus-debug-calibre; fi && if [[ -e .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-preconditions.py ]]; then chmod +x .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-preconditions.py && cp -f .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-preconditions.py 25-cadence-innovus-debug-calibre; fi && if [[ -e .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-postconditions.py ]]; then chmod +x .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-postconditions.py && cp -f .mflowgen/25-cadence-innovus-debug-calibre/mflowgen-check-postconditions.py 25-cadence-innovus-debug-calibre; fi && cd 25-cadence-innovus-debug-calibre && if [[ -e mflowgen-check-preconditions.py ]]; then ./mflowgen-check-preconditions.py || exit 1; fi && ./mflowgen-run 2>&1 | tee mflowgen-run.log || exit 1 && cd .. && touch -c 25-cadence-innovus-debug-calibre/outputs/*

                    _                   _                                               _   _   _                    
  ___    __ _    __| |                 | |__    _   _    __ _             ___    __ _  | | (_) | |__    _ __    ___  
 / __|  / _` |  / _` |                 | '_ \  | | | |  / _` |  ______   / __|  / _` | | | | | | '_ \  | '__|  / _ \ 
| (__  | (_| | | (_| |      _   _      | |_) | | |_| | | (_| | |______| | (__  | (_| | | | | | | |_) | | |    |  __/ 
 \___|  \__,_|  \__,_|     (_) (_)     |_.__/   \__,_|  \__, |           \___|  \__,_| |_| |_| |_.__/  |_|     \___| 
                                                        |___/                                                        

Cadence Innovus(TM) Implementation System.
Copyright 2019 Cadence Design Systems, Inc. All rights reserved worldwide.

Version:	v19.18-s072_1, built Thu Apr 8 10:55:52 PDT 2021
Options:	-overwrite -init innovus-foundation-flow/custom-scripts/run-debug.tcl -log logs/debug.log 
Date:		Sun Sep 17 03:46:42 2023
Host:		ic (x86_64 w/Linux 2.6.32-754.35.1.el6.x86_64) (8cores*8cpus*Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz 16384KB)
OS:		CentOS release 6.10 (Final)

License:
		invs	Innovus Implementation System	19.1	checkout succeeded
		8 CPU jobs allowed with the current license(s). Use setMultiCpuUsage to set your required CPU count.
Create and set the environment variable TMPDIR to /tmp/innovus_temp_8970_ic_sujf_fK23KX.

Change the soft stacksize limit to 0.2%RAM (31 mbytes). Set global soft_stack_size_limit to change the value.
Sourcing startup file ./enc.tcl
****ERROR: (IMPSYT-6689):	Invalid return code while sourcing "./enc.tcl". Check and correct your Tcl script regarding below message:
 can't read "CALIBRE_HOME": no such variable**

**INFO:  MMMC transition support version v31-84 

Sourcing file "innovus-foundation-flow/custom-scripts/run-debug.tcl" ...
#% Begin load design ... (date=09/17 03:46:52, mem=522.7M)
Set Default Input Pin Transition as 0.1 ps.
Loading design 'GcdUnit' saved by 'Innovus' '19.18-s072_1' on 'Sat Sep 16 22:20:31 2023'.
% Begin Load MMMC data ... (date=09/17 03:46:52, mem=525.0M)
% End Load MMMC data ... (date=09/17 03:46:52, total cpu=0:00:00.0, real=0:00:00.0, peak res=525.2M, current mem=525.2M)

Loading LEF file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/libs/lef/rtk-tech.lef ...

Loading LEF file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/libs/lef/stdcells.lef ...
Set DBUPerIGU to M2 pitch 380.

viaInitial starts at Sun Sep 17 03:46:52 2023
viaInitial ends at Sun Sep 17 03:46:52 2023

##  Both design process and tech node are not set.

Loading view definition file from /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/viewDefinition.tcl
Reading libs_typical timing library '/home/sujf/Documents/digital/mflowgen-master/build/1-freepdk-45nm/view-standard/stdcells.lib' ...
Read 135 cells in library 'NangateOpenCellLibrary' 
Reading libs_bc timing library '/home/sujf/Documents/digital/mflowgen-master/build/1-freepdk-45nm/view-standard/stdcells-bc.lib' ...
Read 135 cells in library 'NangateOpenCellLibrary' 
Starting consistency checks on late and early library sets of delay corner 'delay_default'
late library set: libs_typical
early library set: libs_bc
Completed consistency checks. Status: Successful
*** End library_loading (cpu=0.01min, real=0.02min, mem=20.0M, fe_cpu=0.25min, fe_real=0.18min, fe_mem=789.8M) ***
% Begin Load netlist data ... (date=09/17 03:46:53, mem=540.8M)
*** Begin netlist parsing (mem=789.8M) ***
Created 135 new cells from 2 timing libraries.
Reading netlist ...
Backslashed names will retain backslash and a trailing blank character.
Reading verilogBinary netlist '/home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/vbin/GcdUnit.v.bin'
Reading binary database version 2 in 1-threaded mode

*** Memory Usage v#1 (Current mem = 802.797M, initial mem = 288.504M) ***
*** End netlist parsing (cpu=0:00:00.0, real=0:00:00.0, mem=802.8M) ***
% End Load netlist data ... (date=09/17 03:46:53, total cpu=0:00:00.0, real=0:00:00.0, peak res=545.3M, current mem=545.3M)
Set top cell to GcdUnit.
Starting consistency checks on late and early library sets of delay corner 'delay_default'
late library set: libs_typical
early library set: libs_bc
Completed consistency checks. Status: Successful
Starting consistency checks on late and early library sets of delay corner 'delay_default'
late library set: libs_typical
early library set: libs_bc
Completed consistency checks. Status: Successful
Hooked 270 DB cells to tlib cells.
Starting recursive module instantiation check.
No recursion found.
Building hierarchical netlist for Cell GcdUnit ...
*** Netlist is unique.
** info: there are 284 modules.
** info: there are 192 stdCell insts.

*** Memory Usage v#1 (Current mem = 830.719M, initial mem = 288.504M) ***
*info: set bottom ioPad orient R0
Generated pitch 1.68 in metal10 is different from 1.6 defined in technology file in preferred direction.
Generated pitch 0.84 in metal8 is different from 0.8 defined in technology file in preferred direction.
Generated pitch 0.84 in metal7 is different from 0.8 defined in technology file in preferred direction.
Set Default Net Delay as 1000 ps.
Set Default Net Load as 0.5 pF. 
Set Default Input Pin Transition as 0.1 ps.
Loading preference file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/gui.pref.tcl ...
##  Design tech node is not set.

Applying the recommended capacitance filtering threshold values for 45nm process node: total_c_th=0, relative_c_th=1 and coupling_c_th=0.1.
	These values will be used by all post-route extraction engines, including TQuantus, IQuantus and Quantus QRC extraction.
	Capacitance filtering mode(-capFilterMode option of the setExtractRCMode) is 'relAndCoup' for all engines.
	The accuracy mode for postRoute effortLevel low extraction will be set to 'high'.
	Default value for EffortLevel(-effortLevel option of the setExtractRCMode) in postRoute extraction mode will be 'medium' if Quantus QRC technology file is specified else 'low'.
setAnalysisMode -usefulSkew already set.
**WARN: (IMPOPT-3602):	The specified path group name Reg2Reg is not defined.
Type 'man IMPOPT-3602' for more detail.
Effort level <high> specified for Reg2Reg path_group
**WARN: (IMPOPT-3602):	The specified path group name Reg2Out is not defined.
Type 'man IMPOPT-3602' for more detail.
Effort level <low> specified for Reg2Out path_group
**WARN: (IMPOPT-3602):	The specified path group name Reg2ClkGate is not defined.
Type 'man IMPOPT-3602' for more detail.
Effort level <low> specified for Reg2ClkGate path_group
**WARN: (IMPOPT-3602):	The specified path group name In2Reg is not defined.
Type 'man IMPOPT-3602' for more detail.
Effort level <low> specified for In2Reg path_group
**WARN: (IMPOPT-3602):	The specified path group name In2Out is not defined.
Type 'man IMPOPT-3602' for more detail.
Effort level <low> specified for In2Out path_group
**WARN: (IMPTCM-77):	Option "-drouteStartIteration" for command setNanoRouteMode is obsolete and will be removed in a future release. The obsolete option still works in this release but to avoid this warning and to ensure compatibility with future releases, remove the obsolete option from your script.
Setting -ignore_DRC to 0. ViaGen will do DRC check while creating vias.
Setting -viarule_preference to default order. ViaGen will consider via rule priority based on the order of appearance in the technology file.
This command "restoreDesign /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat ..." required an extra checkout of license tpsxl.
Additional license(s) checked out: 1 'Tempus_Timing_Signoff_XL' license(s)
*Info: initialize multi-corner CTS.
Reading timing constraints file '/home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/mmmc/modes/constraints_default/constraints_default.sdc' ...
Current (total cpu=0:00:15.6, real=0:00:11.0, peak res=804.6M, current mem=788.1M)
GcdUnit
INFO (CTE): Constraints read successfully.
Ending "Constraint file reading stats" (total cpu=0:00:00.0, real=0:00:00.0, peak res=807.2M, current mem=807.2M)
Current (total cpu=0:00:15.6, real=0:00:11.0, peak res=807.2M, current mem=807.2M)
Reading latency file '/home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/mmmc/views/analysis_default/latency.sdc' ...
Total number of combinational cells: 100
Total number of sequential cells: 29
Total number of tristate cells: 6
Total number of level shifter cells: 0
Total number of power gating cells: 0
Total number of isolation cells: 0
Total number of power switch cells: 0
Total number of pulse generator cells: 0
Total number of always on buffers: 0
Total number of retention cells: 0
List of usable buffers: BUF_X1 BUF_X2 BUF_X4 BUF_X8 BUF_X16 BUF_X32 CLKBUF_X1 CLKBUF_X2 CLKBUF_X3
Total number of usable buffers: 9
List of unusable buffers:
Total number of unusable buffers: 0
List of usable inverters: INV_X1 INV_X2 INV_X4 INV_X8 INV_X16 INV_X32
Total number of usable inverters: 6
List of unusable inverters:
Total number of unusable inverters: 0
List of identified usable delay cells:
Total number of identified usable delay cells: 0
List of identified unusable delay cells:
Total number of identified unusable delay cells: 0
No delay cells were detected in the set of buffers. Buffers will be used to fix hold violations.
Reading floorplan file - /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.fp.gz (mem = 1111.9M).
% Begin Load floorplan data ... (date=09/17 03:46:53, mem=828.9M)
*info: reset 270 existing net BottomPreferredLayer and AvoidDetour
net ignore based on current view = 0
Deleting old partition specification.
Set FPlanBox to (0 0 94240 90720)
Generated pitch 1.68 in metal10 is different from 1.6 defined in technology file in preferred direction.
Generated pitch 0.84 in metal8 is different from 0.8 defined in technology file in preferred direction.
Generated pitch 0.84 in metal7 is different from 0.8 defined in technology file in preferred direction.
 ... processed partition successfully.
Reading binary special route file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.fp.spr.gz (Created by Innovus v19.18-s072_1 on Sat Sep 16 22:20:29 2023, version: 1)
Ending "Read special route file" (total cpu=0:00:00.0, real=0:00:00.0, peak res=831.7M, current mem=831.7M)
There are 4 nets with weight being set
There are 4 nets with bottomPreferredRoutingLayer being set
There are 4 nets with avoidDetour being set
Extracting standard cell pins and blockage ...... 
Pin and blockage extraction finished
Delete all existing relative floorplan constraints.
% End Load floorplan data ... (date=09/17 03:46:53, total cpu=0:00:00.0, real=0:00:00.0, peak res=832.3M, current mem=830.3M)
Reading congestion map file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.route.congmap.gz ...
% Begin Load SymbolTable ... (date=09/17 03:46:53, mem=830.5M)
Suppress "**WARN ..." messages.
Un-suppress "**WARN ..." messages.
% End Load SymbolTable ... (date=09/17 03:46:53, total cpu=0:00:00.0, real=0:00:00.0, peak res=830.7M, current mem=830.7M)
Loading place ...
% Begin Load placement data ... (date=09/17 03:46:53, mem=830.7M)
Reading placement file - /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.place.gz.
** Reading stdCellPlacement_binary (Created by Innovus v19.18-s072_1 on Sat Sep 16 22:20:29 2023, version# 2) ...
Read Views for adaptive view pruning ...
Read 0 views from Binary DB for adaptive view pruning
*** Checked 2 GNC rules.
*** applyConnectGlobalNets disabled.
*** Completed restorePlace (cpu=0:00:00.0 real=0:00:00.0 mem=1109.9M) ***
Total net length = 2.738e+03 (1.611e+03 1.128e+03) (ext = 1.585e+03)
% End Load placement data ... (date=09/17 03:46:54, total cpu=0:00:00.0, real=0:00:01.0, peak res=834.0M, current mem=832.0M)
Reading PG file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.pg.gz
*** Completed restorePGFile (cpu=0:00:00.0 real=0:00:00.0 mem=1105.9M) ***
% Begin Load routing data ... (date=09/17 03:46:54, mem=832.0M)
Reading routing file - /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.route.gz.
Reading Innovus routing data (Created by Innovus v19.18-s072_1 on Sat Sep 16 22:20:30 2023 Format: 19.1) ...
*** Total 252 nets are successfully restored.
*** Completed restoreRoute (cpu=0:00:00.0 real=0:00:00.0 mem=1110.9M) ***
% End Load routing data ... (date=09/17 03:46:54, total cpu=0:00:00.0, real=0:00:00.0, peak res=837.6M, current mem=836.6M)
TAT_INFO: restoreCongMap REAL = 0 : CPU = 0 : MEM = 0.
Reading property file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit.prop
*** Completed restoreProperty (cpu=0:00:00.0 real=0:00:00.0 mem=1116.9M) ***
Set Default Input Pin Transition as 0.1 ps.
Extraction setup Started 
Initializing multi-corner RC extraction with 1 active RC Corners ...
Reading Capacitance Table File /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/libs/mmmc/rtk-typical.captable ...
Cap table was created using Encounter 08.10-p004_1.
Process name: master_techFreePDK45.
Importing multi-corner RC tables ... 
Summary of Active RC-Corners : 
 
 Analysis View: analysis_default
    RC-Corner Name        : typical
    RC-Corner Index       : 0
    RC-Corner Temperature : 25 Celsius
    RC-Corner Cap Table   : '/home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/libs/mmmc/rtk-typical.captable'
    RC-Corner PreRoute Res Factor         : 1
    RC-Corner PreRoute Cap Factor         : 1
    RC-Corner PostRoute Res Factor        : 1 {1 1 1}
    RC-Corner PostRoute Cap Factor        : 1 {1 1 1}
    RC-Corner PostRoute XCap Factor       : 1 {1 1 1}
    RC-Corner PreRoute Clock Res Factor   : 1	[Derived from postRoute_res (effortLevel low)]
    RC-Corner PreRoute Clock Cap Factor   : 1	[Derived from postRoute_cap (effortLevel low)]
    RC-Corner PostRoute Clock Cap Factor  : 1 {1 1 1} 	[Derived from postRoute_cap (effortLevel low)]
    RC-Corner PostRoute Clock Res Factor  : 1 {1 1 1} 	[Derived from postRoute_res (effortLevel low)]
Initializing multi-corner capacitance tables ... 
Initializing multi-corner resistance tables ...
Loading path group file /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/mmmc/pathgroup.sdc ...
Current (total cpu=0:00:16.1, real=0:00:12.0, peak res=853.3M, current mem=853.3M)
INFO (CTE): Constraints read successfully.
Ending "Constraint file reading stats" (total cpu=0:00:00.0, real=0:00:00.0, peak res=858.1M, current mem=858.1M)
Current (total cpu=0:00:16.1, real=0:00:12.0, peak res=858.1M, current mem=858.1M)
Start generating vias ...
#Skip building auto via since it is not turned on.
Extracting standard cell pins and blockage ...... 
Pin and blockage extraction finished
Via generation completed.
% Begin Load power constraints ... (date=09/17 03:46:54, mem=860.8M)
source /home/sujf/Documents/digital/mflowgen-master/build/16-cadence-innovus-signoff/checkpoints/design.checkpoint/save.enc.dat/GcdUnit_power_constraints.tcl
'set_default_switching_activity' finished successfully.
** WARN:  (VOLTUS_POWR-3212): The 'set_power_analysis_mode -leakage_power_view |-dynamic_power_view|-analysis_view' will be obsolete in 18.20 release. Use 'set_analysis_view -leakage <> | -dynamic <>' to set leakage and dynamic power views.

% End Load power constraints ... (date=09/17 03:46:54, total cpu=0:00:00.0, real=0:00:00.0, peak res=860.8M, current mem=860.6M)
% Begin load AAE data ... (date=09/17 03:46:54, mem=860.6M)
AAE DB initialization (MEM=1147.28 CPU=0:00:00.2 REAL=0:00:00.0) 
% End load AAE data ... (date=09/17 03:46:54, total cpu=0:00:00.4, real=0:00:00.0, peak res=865.6M, current mem=865.6M)
Restoring CCOpt config...
  Extracting original clock gating for ideal_clock...
    clock_tree ideal_clock contains 34 sinks and 2 clock gates.
    Extraction for ideal_clock complete.
  Extracting original clock gating for ideal_clock done.
  The skew group ideal_clock/constraints_default was created. It contains 34 sinks and 1 sources.
  The skew group ideal_clock/constraints_default was created. It contains 34 sinks and 1 sources.
Restoring CCOpt config done.
Total number of combinational cells: 100
Total number of sequential cells: 29
Total number of tristate cells: 6
Total number of level shifter cells: 0
Total number of power gating cells: 0
Total number of isolation cells: 0
Total number of power switch cells: 0
Total number of pulse generator cells: 0
Total number of always on buffers: 0
Total number of retention cells: 0
List of usable buffers: BUF_X1 BUF_X2 BUF_X4 BUF_X8 BUF_X16 BUF_X32 CLKBUF_X1 CLKBUF_X2 CLKBUF_X3
Total number of usable buffers: 9
List of unusable buffers:
Total number of unusable buffers: 0
List of usable inverters: INV_X1 INV_X2 INV_X4 INV_X8 INV_X16 INV_X32
Total number of usable inverters: 6
List of unusable inverters:
Total number of unusable inverters: 0
List of identified usable delay cells:
Total number of identified usable delay cells: 0
List of identified unusable delay cells:
Total number of identified unusable delay cells: 0
No delay cells were detected in the set of buffers. Buffers will be used to fix hold violations.
**WARN: (IMPCTE-107):	The following globals have been obsoleted since version 19.18-s072_1. They will be removed in the next release. 
timing_enable_default_delay_arc
#% End load design ... (date=09/17 03:46:55, total cpu=0:00:02.3, real=0:00:03.0, peak res=868.6M, current mem=868.6M)

*** Summary of all messages that are not suppressed in this session:
Severity  ID               Count  Summary                                  
WARNING   IMPOPT-3602          5  The specified path group name %s is not ...
WARNING   IMPCTE-107           1  The following globals have been obsolete...
WARNING   IMPTCM-77            1  Option "%s" for command %s is obsolete a...
*** Message Summary: 7 warning(s), 0 error(s)

The timeout for a remote job to respond is 3600 seconds.
Submit command for task runs will be: local
**WARN: (PRL-39):	Number of local CPUs specified (16) > Actual number of CPUs in the host (8). The lower value will be used.
<FF> Plugin -> always_source_tcl
<FF> LOADING 'always_source_tcl' PLUG-IN FILE(s) 
<FF> -> innovus-foundation-flow/custom-scripts/always-source.tcl
innovus 1> exit

*** Memory Usage v#1 (Current mem = 1156.414M, initial mem = 288.504M) ***
*** Message Summary: 8 warning(s), 1 error(s)

--- Ending "Innovus" (totcpu=0:00:17.6, real=0:00:18.0, mem=1156.4M) ---

touch 25-cadence-innovus-debug-calibre/.execstamp.execute-phony
cd 25-cadence-innovus-debug-calibre && if [[ -e mflowgen-check-postconditions.py ]]; then ./mflowgen-check-postconditions.py || exit 1; fi && cd ..
touch 25-cadence-innovus-debug-calibre/.postconditions.stamp

**Comment by sujf** [comment]
my linux environment is bash

**Comment by steveri** [comment]
>  **ERROR: (IMPSYT-6689): Invalid return code while sourcing "./enc.tcl". Check and correct your Tcl script regarding below message:
 can't read "CALIBRE_HOME": no such variable

Maybe add this at the top of your `./enc.tcl` file:
```
set CALIBRE_HOME "/opt/mentor/Calibre2015/aoi_cal_2015.2_36.27"
```

and/or maybe
```
set CALIBRE_HOME  $::env(CALIBRE_HOME)
```

**Comment by sujf** [comment]
thanks,your way is work
