### ISSUE TITLE
Mflowgen version not updated after major change (param update)

### ISSUE THREAD

**Issue by Gu3nol** [mflowgen/mflowgen#158]
Hey Chris,

Long time no see :) 

You recently added the param update feature in mflowgen (with the param_handler.py). It's a major feature addition. Still, the version of mflowgen is still 0.5.0.

I would suggest switching to 0.6.0. 

Best,

Guénolé

PS: Yes, still using mflowgen regularly after all these years. :)

**Comment by ctorng** [comment]
Haha, updated to 0.6.0.
