### ISSUE TITLE
Preventing blockage-related DRC errors in signoff

### ISSUE THREAD

**Issue by steveri** [mflowgen/mflowgen#86]
Apparently the signoff step runs a script from foundation flow `innovus-foundation-flow/INNOVUS/run_signoff.tcl`, which in turn runs a `verify_drc` command that, on our design (garnet) yields the maximum 1000 violations.
```
% less /build/gold.158/full_chip/30-cadence-innovus-signoff/mflowgen-run.log
  # verify_drc
  ...
  Verification Complete : 1000 Viols
```
The violations mostly go away (all but five or so) if we delete all the routing blockages first:
```
    select_obj [get_db route_blockages]
    deleteSelectedFromFPlan
    verify_drc
```
I'm tempted to recommend that the delete-blockages be added as part of run_signoff, but maybe that's not the best place? Other options might include:
* remove blockages as a separate step
* ?

(Note there is another script `innovus-foundation-flow/INNOVUS/run_simple.tcl` that also runs `verify_drc`, but I don't know what its full role is in the flow...)

**Comment by ctorng** [comment]
The run_simple.tcl script is not used in any mflowgen steps.

**Comment by ctorng** [comment]
I think fiddling with routing blockages should be something you customize Amber for... so you add the script "submodularly" just like how we add custom-init scripts, etc.

**Comment by steveri** [comment]
That's a good idea, I will do that. We can close the issue.
